# Generated by Django 4.0.3 on 2022-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=50)),
                ('imagen_noticia', models.ImageField(upload_to='')),
                ('descripcion_noticia', models.CharField(max_length=200)),
                ('noticia_noticia', models.CharField(max_length=2000)),
            ],
        ),
    ]
