# Generated by Django 4.0.5 on 2022-07-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0004_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_staff', models.ImageField(upload_to='images/')),
                ('nombre_staff', models.CharField(max_length=20)),
                ('descripcion_staff', models.CharField(max_length=200)),
            ],
        ),
    ]
