# Generated by Django 4.0.5 on 2022-07-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imange_curso', models.ImageField(upload_to='')),
                ('nombre_curso', models.CharField(max_length=20)),
                ('descripcion_curso', models.CharField(max_length=300)),
            ],
        ),
    ]
