# Generated by Django 4.0.5 on 2022-07-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0007_rename_imange_curso_curso_imagen_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor_curso',
            field=models.CharField(default='profesor', max_length=30),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen_curso',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(max_length=40),
        ),
    ]
