# Generated by Django 4.0.5 on 2022-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0008_curso_profesor_curso_alter_curso_imagen_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion_detalle_curso',
            field=models.CharField(default='Detalle', max_length=600),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_curso',
            field=models.IntegerField(default='0', max_length=5),
        ),
    ]
