# Generated by Django 4.0.3 on 2022-07-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0010_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio_curso',
            field=models.IntegerField(default='0'),
        ),
    ]
