# Generated by Django 4.0.3 on 2022-07-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0011_alter_curso_precio_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=20)),
                ('apellido_profesor', models.CharField(max_length=20)),
                ('curso_profesor', models.CharField(choices=[('Escultura sobre marmol', 'Escultura sobre marmol'), ('Arte rupestre', 'Arte rupestre'), ('Surrealismo', 'Surrealismo')], max_length=40)),
                ('imagen_profesor', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
