# Generated by Django 4.0.5 on 2022-07-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0013_profesores_biografia_profesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=40)),
                ('apellido_estudiante', models.CharField(max_length=30)),
                ('email_estudiante', models.EmailField(max_length=254)),
                ('dni_estudiante', models.IntegerField()),
                ('curso_estudiante', models.CharField(max_length=20)),
            ],
        ),
    ]
