# Generated by Django 4.0.3 on 2022-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia_Arte', '0015_alter_estudiante_dni_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='curso_estudiante',
            field=models.CharField(choices=[('Escultura sobre marmol', 'Escultura sobre marmol'), ('Arte rupestre', 'Arte rupestre'), ('Surrealismo', 'Surrealismo')], max_length=50),
        ),
    ]
